- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/Users/sharanak/.jenkins/workspace/ansible/target/MyAnsibleApp01.war"
        dest: "/opt/homebrew/bin/ansible-playbook"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
